const generatedBibEntries = {
    "8460962": {
        "abstract": "An autonomous mobile robot operating in an unstructured environment must be able to deal with dynamic changes of the environment. Navigation and control of a mobile robot in an unstructured environment are one of the most challenging problems. Fuzzy logic control is a useful tool in the field of navigation of mobile robot. In this research, fuzzy logic controller is optimized by integrating fuzzy logic with other soft computing techniques like genetic algorithm, neural networks, and Particle Swarm Optimization (PSO). Soft computing techniques are used in this work to tune the membership function parameters of fuzzy logic controller to improve the navigation performance. Four methods have been designed and implemented: manually constructed fuzzy logic (M-Fuzzy), fuzzy logic with genetic algorithm (GA-Fuzzy), fuzzy logic with neural network (Neuro-Fuzzy), and fuzzy logic with PSO (PSO-Fuzzy). The performances of these approaches are compared through computer simulations and experiment number of scenarios using Khepera III mobile robot platform. Hybrid fuzzy logic controls with soft computing techniques are found to be most efficient for mobile robot navigation. The GA-Fuzzy technique is found to perform better than the other techniques in most of the test scenarios in terms of travelling time and average speed. The performances of both PSO-Fuzzy and Neuro-Fuzzy are found to be better than the other methods in terms of distance travelled. In terms of bending energy, the PSO-Fuzzy and Neuro-Fuzzy are found to be better in simulation results. Although, the M-Fuzzy is found to be better using real experimental results. Hence, the most important system parameter will dictate which of the four methods to use",
        "author": "Mohammed Algabri, Hassan Mathkour, Hedjar Ramdane, Mansour Alsulaiman",
        "booktitle": "COMPARATIVE STUDY OF SOFT COMPUTING TECHNIQUES FOR MOBILE ROBOT NAVIGATION IN AN UNKNOWN ENVIRONMENT",
        "doi": "https://doi.org/10.1016/j.chb.2015.03.062",
        "keywords": "Mobile robot navigation;Soft computing;Fuzzy logic;Genetic algorithm;Particle swarm optimization ANFIS",
        "pages": "42-56",
        "title": "Real Time Semantic Segmentation of Crop and Weed for Precision Agriculture Robots Leveraging Background Knowledge in CNNs",
        "type": "INPROCEEDINGS",
        "url": "https://www.sciencedirect.com/science/article/pii/S0747563215002605?casa_token",
        "volume": "50",
        "year": "2015"
    },
    "8826846": {
        "abstract": "Navigation is a fundamental problem of mobile robots, for which Deep Reinforcement Learning (DRL) has received significant attention because of its strong representation and experience learning abilities. There is a growing trend of applying DRL to mobile robot navigation. In this paper, we review DRL methods and DRL-based navigation frameworks. Then we systematically compare and analyze the relationship and differences between four typical application scenarios: local obstacle avoidance, indoor navigation, multi-robot navigation, and social navigation. Next, we describe the development of DRL-based navigation. Last, we discuss the challenges and some possible solutions regarding DRL-based navigation.",
        "author": "Kai Zhu, Tao Zhang",
        "booktitle": "2019 IEEE International Instrumentation and Measurement Technology Conference (I2MTC)",
        "cited": "164",
        "doi": "10.26599/TST.2021.9010012",
        "issn": "1007-0214",
        "issue": "5",
        "keywords": "Navigation;Mobile robots;Reinforcement learning;Simultaneous localization and mapping;Robots Task analysis;Robot sensing systems",
        "pages": "674-691 1-6",
        "title": "Deep reinforcement learning based mobile robot navigation: A review",
        "type": "INPROCEEDINGS",
        "url": "https://ieeexplore.ieee.org/abstract/document/9409758/authors",
        "volume": "26",
        "year": "2021"
    },
    "9001903": {
        "abstract": "Mobile robots have been widely implemented in industrial automation and smart factories. Different types of mobile robots work cooperatively in the workspace to complete some complicated tasks. Therefore, the main requirement for multi-robot systems is collision-free navigation in dynamic environments. In this paper, we propose a sensor network based navigation system for ground mobile robots in dynamic industrial cluttered environments. A range finder sensor network is deployed on factory floor to detect any obstacles in the field of view and perform a global navigation for any robots simultaneously travelling in the factory. The obstacle detection and robot navigation are integrated into the sensor network and the robot is only required for a low-level path tracker. The novelty of this paper is to propose a sensor network based navigation system with a novel artificial potential field (APF) based navigation algorithm. Computer simulations and experiments confirm the performance of the proposed method.",
        "author": "Hang Li, Andrey V. Savkin",
        "booktitle": "AN ALGORITHM FOR SAFE NAVIGATION OF MOBILE ROBOTS BY A SENSOR NETWORK IN DYNAMIC CLUTTERED INDUSTRIAL ENVIRONMENTS",
        "doi": "https://doi.org/10.1016/j.rcim.2018.05.008",
        "keywords": "Obstacle avoidance;Industrial mobile robots;Dynamic environments;Sensor network;Safe robot navigation;Industrial automation",
        "pages": "65-82",
        "title": "Moment Invariant Based Weed/Crop Discrimination For Smart Farming",
        "type": "INPROCEEDINGS",
        "url": "https://www.sciencedirect.com/science/article/pii/S0736584517300844?casa_token",
        "volume": "54",
        "year": "2018"
    },
    "9298209": {
        "abstract": "Mobile robots can travel by acquiring the information using sensor-actuator control techniques from surrounding and perform several tasks. Due to the ability of traversing, mobile robots are used in different application for different places. In the field of robotic research, robot navigation is the fundamental problem and it is easier in static environment than dynamic environment. This paper presents a new method for generating a collision-free, near-optimal path and speed for a mobile robot in a dynamic environment containing moving and static obstacles using artificial neural network. For each robot motion, the workspace is divided into five equal segments. The multilayer perceptron (MLP) neural network is used to choose a collision-free segment and also controls the speed of the robot for each motion. Simulation results show that the method is efficient and gives near-optimal path reaching the target position of the mobile robot.",
        "author": "Ngangbam Herojit Singh & Khelchandra Thongam ",
        "booktitle": "Intelligent Service Robotics",
        "doi": "https://doi.org/10.1007/s11370-018-0260-2",
        "keywords": "Mobile robot;Path planning;Dynamic environment;Artificial neural network;Obstacle avoidance;Collision-free path;Supervised learning;Multilayer perceptron",
        "pages": "55-67",
        "title": "Neural network-based approaches for mobile robot navigation in static and moving obstacles environments",
        "type": "INPROCEEDINGS",
        "url": "https://link.springer.com/article/10.1007/s11370-018-0260-2",
        "volume": "12",
        "year": "2018"
    },
    "ABOUZAHIR2021179": {
        "abstract": "This paper presents a literature survey and a comparative study of Bug Algorithms, with the goal of investigating their potential for robotic navigation. At first sight, these methods seem to provide an efficient navigation paradigm, ideal for implementations on tiny robots with limited resources. Closer inspection, however, shows that many of these Bug Algorithms assume perfect global position estimate of the robot which in GPS-denied environments implies considerable expenses of computation and memory \u2014 relying on accurate Simultaneous Localization And Mapping (SLAM) or Visual Odometry (VO) methods. We compare a selection of Bug Algorithms in a simulated robot and environment where they endure different types noise and failure-cases of their on-board sensors. From the simulation results, we conclude that the implemented Bug Algorithms\u2019 performances are sensitive to many types of sensor-noise, which was most noticeable for odometry-drift. This raises the question if Bug Algorithms are suitable for real-world, on-board, robotic navigation as is. Variations that use multiple sensors to keep track of their progress towards the goal, were more adept in completing their task in the presence of sensor-failures. This shows that Bug Algorithms must spread their risk, by relying on the readings of multiple sensors, to be suitable for real-world deployment.",
        "author": "K.N. McGuire, G.C.H.E. de Croon, K. Tuyls",
        "doi": "https://doi.org/10.1016/j.robot.2019.103261",
        "journal": "Robotic and Autonomous Systems",
        "keywords": "Bug algorithms;Robotic navigation;Comparative study;Limited sensing;Indoor navigation",
        "number": "",
        "pages": "",
        "title": "A comparative study of bug algorithms for robot navigation",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S0921889018306687?casa_token",
        "volume": "121",
        "year": "2019"
    },
    "AHMAD2021106081": {
        "abstract": "Robots are increasingly operating in indoor environments designed for and shared with people. However, robots working safely and autonomously in uneven and unstructured environments still face great challenges. Many modern indoor environments are designed with wheelchair accessibility in mind. This presents an opportunity for wheeled robots to navigate through sloped areas while avoiding staircases. In this paper, we present an integrated software and hardware system for autonomous mobile robot navigation in uneven and unstructured indoor environments. This modular and reusable software framework incorporates capabilities of perception and navigation. Our robot first builds a 3D OctoMap representation for the uneven environment with the 3D mapping using wheel odometry, 2D laser and RGB-D data. Then we project multilayer 2D occupancy maps from OctoMap to generate the the traversable map based on layer differences. The safe traversable map serves as the input for efficient autonomous navigation. Furthermore, we employ a variable step size Rapidly Exploring Random Trees that could adjust the step size automatically, eliminating tuning step sizes according to environments. We conduct extensive experiments in simulation and real-world, demonstrating the efficacy and efficiency of our system. (Supplemented video link: https://youtu.be/6XJWcsH1fk0).",
        "author": "Chaoqun Wang; Lili Meng; Sizhen She; Ian M. Mitchell; Teng Li; Frederick Tung; Weiwei Wan; Max. Q.-H. Meng; Clarence W. de Silva",
        "doi": "10.1109/IROS.2017.8202145",
        "issn": "2153-0866",
        "keywords": "Mobile robots;Three-dimensional displays;Navigation;Two dimensional displays;Simultaneous localization and mapping",
        "title": "Autonomous mobile robot navigation in uneven and unstructured indoor environments",
        "type": "article",
        "url": "https://ieeexplore.ieee.org/abstract/document/8202145/authors",
        "year": "2017"
    },
    "ASAD2020535": {
        "abstract": "This paper presents a new design approach for an intelligent navigation algorithm for omnidirectional mobile robots. Unlike the previous works dealing with the navigation of omnidirectional robots that are focused on only the estimation of the final position, the main contribution of the present study is summed up in the fact that the robot has to reach the final desired position with a predefined final steering angle. This latter improvement is a part of researches carried out on Intelligent Transport Systems (ITS). Taking into consideration the drawbacks of proportional integral (PI) control when applied to omnidirectional robot navigation, we develop an approach to design a fuzzy logic PI controller (Fuzzy-PI).Preliminary simulation and experimental results using the Fuzzy-PI controller have shown limitations as the robot performed a larger path when the desired final angle increased. Thus, a deepen study have concluded that the Fuzzy-PI system cannot control at the same time the linear and angular velocities. To overcome these drawbacks, we propose to replace the previous intelligent navigation system by two independent controllers. The designed Fuzzy-PI controllers can adjust their parameters (KP, KI) to reduce the error caused by the dynamic changes and navigation challenges of omnidirectional robot. A navigation algorithm cannot be efficient without obstacle avoidance system. To achieve this goal, we have developed a third fuzzy controller to fulfill this task.To evaluate the real performances of fuzzy controllers for navigation and obstacles avoidance, simulation and experimental tests are performed for one, two and three obstacles. The obtained results confirm that the omnidirectional robot could navigate in an unstructured and unknown obstacles environment with better performances and efficiency.",
        "author": "Mohamed Slim Masmoudi, Najla Krichen, Mohamed Masmoudi, Nabil Derbel",
        "doi": "https://doi.org/10.1016/j.asoc.2016.08.057",
        "keywords": "Omnidirectional robot;Kinematic model;Navigation Fuzzy-PI;Optimization Obstacle avoidance",
        "pages": "901-919",
        "title": "Fuzzy logic controllers design for omnidirectional mobile robot navigation",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S1568494616304598?casa_token",
        "volume": "49",
        "year": "2016"
    },
    "ESPEJOGARCIA202179": {
        "abstract": "In recent years, automatic weed control has emerged as a promising alternative for reducing the amount of herbicide applied to the field, instead of conventional spraying. The use of artificial intelligence through the implementation of deep learning for early weeds identification has been one of the engines to boost this progress. However, these techniques usually need very large datasets coping with real-world conditions, which are scarce in the agricultural domain. To address the lack of such datasets, this paper proposes a methodology that combines the use of agricultural transfer learning and the creation of artificial images by generative adversarial networks (GANs). Several architectures and configurations have been evaluated on a dataset containing images of tomato and black nightshade. The best configuration was a combination of GANs creating plausible synthetic images and the Xception network, with a performance of 99.07% on the test set and 93.23% on a noisy version of the same set. Other architectures, such as Inception or DenseNet have also been evaluated, and they obtained promising results by using GANs. According to the results, the combination of advanced transfer learning and data augmentation techniques through GANs should be deeply studied in the future with more complex datasets.",
        "author": "Ngangbam Herojit Singh, Khelchandra Thongam",
        "doi": "https://doi.org/10.1016/j.procs.2017.12.004",
        "keywords": "Type your keywords;hereseparated by semicolons",
        "pages": "11-17",
        "title": "Mobile Robot Navigation Using Fuzzy Logic in Static Environments",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S1877050917327680",
        "volume": "125",
        "year": "2018"
    },
    "ZHENG2017215": {
        "abstract": "The aim of this paper is to provide a global overview of mobile robot control and navigation methodologies developed over the last decades. Mobile robots have been a substantial contributor to the welfare of modern society over the years, including the industrial, service, medical, and socialization sectors. The paper starts with a list of books on autonomous mobile robots and an overview of survey papers that cover a wide range of decision, control and navigation areas. The organization of the material follows the structure of the author\u2019s recent book on mobile robot control. Thus, the following aspects of wheeled mobile robots are considered: kinematic modeling, dynamic modeling, conventional control, affine model-based control, invariant manifold-based control, model reference adaptive control, sliding-mode control, fuzzy and neural control, vision-based control, path and motion planning, localization and mapping, and control and software architectures.",
        "author": "Spyros G.Tzafestas",
        "doi": "https://doi.org/10.1007/s10846-018-0805-9",
        "journal": "Journal of Intelligent & Robotic Systems",
        "keywords": "Mobile robot;Autonomous mobile robot;Control Path planning;Motion planning;Navigation;Localization;Mapping;Control architecture;Software architecture",
        "pages": "35-58",
        "title": "Mobile Robot Control and Navigation: A Global Overview",
        "type": "article AI",
        "url": "https://link.springer.com/article/10.1007/s10846-018-0805-9",
        "volume": "91",
        "year": "2018"
    },
    "s20020455": {
        "abstract": "This paper presents the rigorous study of mobile robot navigation techniques used so far. The step by step investigations of classical and reactive approaches are made here to understand the development of path planning strategies in various environmental conditions and to identify research gap. The classical approaches such as cell decomposition (CD), roadmap approach (RA), artificial potential field (APF); reactive approaches such as genetic algorithm (GA), fuzzy logic (FL), neural network (NN), firefly algorithm (FA), particle swarm optimization (PSO), ant colony optimization (ACO), bacterial foraging optimization (BFO), artificial bee colony (ABC), cuckoo search (CS), shuffled frog leaping algorithm (SFLA) and other miscellaneous algorithms (OMA) are considered for study. The navigation over static and dynamic condition is analyzed (for single and multiple robot systems) and it has been observed that the reactive approaches are more robust and perform well in all terrain when compared to classical approaches. It is also observed that the reactive approaches are used to improve the performance of the classical approaches as a hybrid algorithm. Hence, reactive approaches are more popular and widely used for path planning of mobile robot. The paper concludes with tabular data and charts comparing the frequency of individual navigational strategies which can be used for specific application in robotics.",
        "author": "B.K. Patle, Ganesh Babu L, Anish Pandey, D.R.K. Parhi, A. Jagadeesh",
        "doi": "https://doi.org/10.1016/j.dt.2019.04.011",
        "keywords": "Mobile robot navigation;Path planning;Classical approaches;Reactive approaches;Artificial intelligence",
        "pages": "582-606",
        "title": "A review: On path planning strategies for navigation of mobile robot",
        "type": "Article @Article{s20020455,",
        "url": "https://www.sciencedirect.com/science/article/pii/S2214914718305130",
        "volume": "15",
        "year": "2019"
    }
};